### ISSUE TITLE
Players, Mobs/Animals when to close

### ISSUE THREAD

**Issue by ThisIsDelyria** [magmafoundation/Magma-1.16.x#110]
When i move to close/into a player or mobs/animals, its buggy and glitchy
its like not moving/pushing the mobs, player, animals instead it is buggy and u r some kind of stuck
(tried it without mods on magma and forge, on forge it does not happen)

    Magma Version: magma-1.16.5-36.1.0-627ed9b

**Comment by jahangir6969** [comment]
#93 ticket already open for this issue.

**Comment by ThisIsDelyria** [comment]
sorry didnt saw it, my bad
