### ISSUE TITLE
[Vanilla] Music disc does not go into Juke box

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#12]
Describe the bug
A clear and concise description of what the bug is:

Not able to place in disc into juke box. 

To Reproduce
Steps to reproduce the behaviour:

Place in music disc into juke box and it does not go in

Expected behaviour
A clear and concise description of what you expected to happen:

For the music disc to go into the juke box and place music

Screenshots
If applicable, add screenshots to help explain your problem:

https://gyazo.com/9626e9c9cf711c928f0575cacf053583

Console Logs:

no errors

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.3 forge 34.1.42
Magma Version: forge-1.16.3-34.1.35-2a697a4
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

**Comment by jahangir6969** [comment]
Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM

**Comment by kwright02** [comment]
I fixed the disc not going in, now I'm just trying to work out actually getting the record to play

**Comment by kwright02** [comment]
Fixed getting the record to play! I'll push the changes when I've fixed some other issues
