### ISSUE TITLE
[Paper maybe?] New version 4f8557f error console when clicking refresh button on mutliplayer screen

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#120]
**Describe the bug**
A clear and concise description of what the bug is:

With version: 4f8557f It error console the moment you click the refresh button on the multiplayer screen

**To Reproduce**
Steps to reproduce the behaviour:

click refresh button and watch console

**Expected behaviour**
A clear and concise description of what you expected to happen:

For it not to spam console

**Screenshots**
If applicable, add screenshots to help explain your problem:

N/A

Also here is the logs for it as well:

https://pastebin.com/dvSBkKtg

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: forge-1.16.5-36.1.32
Magma Version: forge-1.16.5-36.1.32-4f8557f-DEV
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by JohanC34** [comment]
Same thing is happening to me
