### ISSUE TITLE
[14Jul2021 22:53:32.930] [Netty Server IO #1/ERROR] [net.minecraft.network.NettyPacketEncoder/]: Error encoding packet

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#127]
Log error: https://mclo.gs/lZSWxXG
Last version
Windows 10

**Comment by JohanC34** [comment]
I have the same error. The server is shown like if its offline, but i can join to it, and when i refresh server screen the console spam something in red, same as yours

**Comment by joaoespanhol** [comment]
update log. https://mclo.gs/Htq5bWf
