### ISSUE TITLE
Incompatible Plugins [1.16.5]

### ISSUE THREAD

**Issue by MathisSkate** [magmafoundation/Magma-1.16.x#130]
Hello !

I have three plugins that is incompatible with Magma for now !

- Tab from https://github.com/NEZNAMY/TAB/releases all Version 

- ProtocolLib : All Version

- Holographics Display : All Version

Can you fix it please ^^

Thanks you !

**Comment by UeberallGebannt** [comment]
Please provide error logs aswell as a more detailed explaination about what isn't working

**Comment by MathisSkate** [comment]
Here is my logs https://hastebin.com/uloqejacuk.yaml

**Comment by Icemallow** [comment]
Any fix?
