### ISSUE TITLE
Modded villager professions break bukkit enum

### ISSUE THREAD

**Issue by Column01** [magmafoundation/Magma-1.16.x#133]
The server crashed when logging in with an IllegalArugmentException. Using latest (`113bec6`) Magma and the modpack: `All the Mods 6`

Crash report is [here](https://gist.github.com/Column01/dad47a60bf9c4f029a95bee56cb1a467) but it states: `No enum constant org.bukkit.entity.Villager.Profession.BEEKEEPER` which appears to be a villager added by Resourceful Bees

**Comment by Column01** [comment]
Did I install something incorrectly?

I followed the instructions in the installation section exactly. The created forge jar is 195kb in size which is way smaller than the ones on the releases page.

**Comment by Column01** [comment]
I reset the world, I built it manually, but this time I did it a bit differently. I used the installer and I also I moved the launcher jar over and added the larger forge jar it built (that has the bukkit/spigot/paper code in it) and it seems to have launched and allows me in. Though I'm still concerned this error might come back at some point out of the blue.

**Comment by Column01** [comment]
See relating class from Resourceful Bees where the villager profession is registered [here](https://github.com/Resourceful-Bees/ResourcefulBees/blob/master/forge/src/main/java/com/teamresourceful/resourcefulbees/registry/ModVillagerProfessions.java)

**Comment by janvdv96** [comment]
We are experiencing the same error with the `Ice and Fire: Dragons` mod and its "Scribe" villager:

`No enum constant org.bukkit.entity.Villager.Profession.SCRIBE`

Also version `113bec6`

**Comment by Column01** [comment]
> We are experiencing the same error with the `Ice and Fire: Dragons` mod and its "Scribe" villager:
> 
> `No enum constant org.bukkit.entity.Villager.Profession.SCRIBE`
> 
> Also version `113bec6`

I've updated the issue title to reflect whats happening. Hopefully we can get this fixed
