### ISSUE TITLE
Server Not Stopping Properly [1.16.5]

### ISSUE THREAD

**Issue by FatalImagine** [magmafoundation/Magma-1.16.x#142]
Having an issue with the server stopping properly, it saves the world, etc but does not fully stop. This results in me having to close the command prompt on my PC or if I'm hosting it through a dedicated server using a panel I have to execute the kill command on the server to have the option to start again.

**Comment by hgaldon** [comment]
Bump, i'm having the same issue

**Comment by reiyooki** [comment]
Same here, tried the last three builds (e8445f4, 4874525, 275780b), all of them have this issue. Result is the same on both Windows and Debian. There's no error message during shutdown, it just hangs after saving worlds requiring the java process to be manually killed.

**Comment by FlyGuyGo** [comment]
I also have this issue when using Valhelsia 3.
