### ISSUE TITLE
Inventory issues after death

### ISSUE THREAD

**Issue by ZhrJosh** [magmafoundation/Magma-1.16.x#145]
Hey.. I'm currently running Endeavour 1.4.0 on the latest Magma release for 1.16.5, whenever you die your inventory stops updating with items that you pick up, you have to click an empty inventory spot for them to show, and even then picking up items after still wont show.

**Comment by SkyLightEffect** [comment]
It's the same with me. The only workaround seems to be to reconnect.

**Comment by Onioncow** [comment]
A kinda jank workaround is if you have curio (and presumably baubles though I haven't tested that) installed. If you press the curio icon in the inventory tab, it will temporarily update your inventory. It doesn't keep updating though, you have to keep pressing the icon. Hopefully this gets fixed soon

**Comment by sippeeey** [comment]
Same here!
I have tested with the latest two 1.16.5 magma jar files. in both are the same problem. without mods it's also the same problem.
hope this will be fixed

**Comment by 848244210** [comment]
Me too.
