### ISSUE TITLE
Various mods require forge 36.2.0 or newer

### ISSUE THREAD

**Issue by SodoPlex** [magmafoundation/Magma-1.16.x#147]
Current version of forge in magma: 36.1.32
installed magma version: magma-1.16.5-36.1.32-4874525-DEV

example error on boot:
-- MOD cofh_core --
Details:
	Mod File: cofh_core-1.16.5-1.3.1.jar
	Failure message: Mod cofh_core requires forge 36.2.0 or above
		Currently, forge is 36.1.32-4874525-DEV
	Mod Version: 1.3.1
	Mod Issue URL: https://github.com/cofh/feedback
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by Jaantheman** [comment]
Wait what is the solution instead of just closing it with no explanation?

**Comment by Irgendwer01** [comment]
@Jaantheman https://github.com/magmafoundation/Magma-1.16.x/commit/4a38de0c2de59ca63db12ac17ef491bba640286a

**Comment by Jaantheman** [comment]
thank you :)
