### ISSUE TITLE
Worldedit bug with magma-1.16.5-36.1.32-275780b-DEV-installer

### ISSUE THREAD

**Issue by greenhawks45** [magmafoundation/Magma-1.16.x#149]
(Gonna list all what i have tried first and then say what the issue is) 

I first encountered this bug when running world edit as a mod in a server with a few mods and plugins. I then tried to switch the mod out for the plugin version, same bug occurred. 

I then removed everything except for the plugin and the mod (not at same time, two separate trials), and the bug still occurred.

I also tried the mod in single player and it works perfectly fine.

So the bug is that everything loads fine, but then in game if you go to type //wand (a basic world edit command), when you hit enter then it sends the "Unknown command" message. The way i know the mod/plugin is loaded and semi working is that the text auto complete shows the auto complete text for all the worldedit commands and will auto complete the commands when you hit tab, but when hitting enter to execute the commands it sends the unknown command message. 

One of the World edit versions used (saw another issue submission on here for world edit issues that mentioned this version working so i tried it [didn't work]): worldedit-forge-mc1.16.3-7.2.2-dist.jar (mod)

Original version of world edit used: worldedit-mod-7.2.5-dist.jar

If you think it is an error on my side just let me know what u need to see and ill send screenshots etc.
Any help is greatly appreciated! :)

**Comment by Eniam** [comment]
I have the same issue.
