### ISSUE TITLE
[Bug]: [Question]: Magma 1.17.1

### ISSUE THREAD

**Issue by lyoneofficial** [magmafoundation/Magma-1.16.x#157]
### What happened?

Hello,
Can you develop an a version of Magma for Minecraft 1.17.1?
Because my server and other much server request it.
Please create it.

### Mods

__

### Mod Version

__

### Magma Version

__

### OS

Windows

### Relevant log output

```shell
__
```

**Comment by MagnusHJensen** [comment]
Bad request.

A lot of time goes into making a hybrid software work, there is still issues on 1.12. 1.16 is still in beta, and also has major issues. 1.17 is still under development from the forge team.

So don't make requests like these, they are disrespectful to the team, who puts their free time into this project. Wait it out. If you look at the discord, you can also see they are slowly working on a 1.17/1.18 version, but not really started yet.

**Comment by MagnusHJensen** [comment]
I'm not the author nor a contributor.

**Comment by lyoneofficial** [comment]
Hello,
How i compile Magma?

**Comment by AwesomeDude091** [comment]
Just download the build from https://magmafoundation.org/

**Comment by lyoneofficial** [comment]
Hello.
I want to edit and recompile Magma for 1.17.1

**Comment by lyoneofficial** [comment]
Hello,
Can i have the version of Magma 1.17.1 that's is in developing?

**Comment by lyoneofficial** [comment]
Hello can you give me Magma for 1.17.1?

**Comment by UeberallGebannt** [comment]
There is no 1.17 version and there most likely will never be one.
It doesn't even build or run yet and was planned as a foundation for Magma 1.18.
