### ISSUE TITLE
[Bug]: OpeNLogin plugin won't start

### ISSUE THREAD

**Issue by GDTwilight** [magmafoundation/Magma-1.16.x#160]
### What happened?

The authorization interface does not appear

### Mods

empty

### Mod Version

empty

### Magma Version

ve8445f4  (1.16.5)

### OS

Linux

### Relevant log output

```shell
[12:32:18] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling nLogin v9.4.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
```

**Comment by Hexeption** [comment]
Fixed
