### ISSUE TITLE
[Vanilla] Enter nether when disable in server.prop no longer kills server but mess with the chunks within the overworld and end

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#17]
Describe the bug
A clear and concise description of what the bug is:

So when the nether is disable in console and you try to enter the nether it crashes the server. 

To Reproduce
Steps to reproduce the behaviour:

set allow-nether to false within server.prop and try to enter nether and then server dead. 

Expected behaviour
A clear and concise description of what you expected to happen:

For the player to be able to sit in the portal and not kill the server

Screenshots
If applicable, add screenshots to help explain your problem:

no video of this just got the console error log thing. 

Console Logs:

https://pastebin.com/4yHLhyn4

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.3 forge 34.1.42
Magma Version: forge-1.16.3-34.1.35-2a697a4
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

**Comment by jahangir6969** [comment]
Very broken within 1.16.5 36.1.0: https://youtu.be/YAFWAaE3D4o

Here the console error as well: https://pastebin.com/ymVdFKB0

**Comment by jahangir6969** [comment]
After an server restart: https://gyazo.com/91ee3977f1b1049611308731b4147509

**Comment by jahangir6969** [comment]
So done some further checks. it no longer kills the server but mess up with chunks within the overworld and end and it spams console due to it: https://pastebin.com/xGLwWbfR

**Comment by Hexeption** [comment]
Fixed
