### ISSUE TITLE
[Bug]: Animals do not drop their items

### ISSUE THREAD

**Issue by ByMessias** [magmafoundation/Magma-1.16.x#181]
### What happened?

What happens is that when an animal is killed it does not leave any items, it only dies without leaving anything

### Mods

None

### Mod Version

(latest builds as of nov 18 2021) - 1.16.5

### Magma Version

v75c9e73

### OS

Linux

**Comment by wallxq** [comment]
I have the same problem..

**Comment by Kitsumei** [comment]
This also seems to apply to all mobs in general, including modded ones.

**Comment by Hexeption** [comment]
A fix coming very soon

**Comment by Cixon** [comment]
> A fix coming very soon

excellent thank u, please!

**Comment by UeberallGebannt** [comment]
@Cixon fixed in latest dev
