### ISSUE TITLE
[IMPORTANT] Stolen Code

### ISSUE THREAD

**Issue by Shawiizz** [magmafoundation/Magma-1.16.x#196]
Hello, few days ago we have noticed that Hexeption pushed [a commit](https://github.com/magmafoundation/Magma-1.16.x/commit/b7e241b19757abded989febcb5ed5bcb8f624a7d) which contains the Mohist's installer code in the Magma 1.16 repository.
We decided to create this issue because too much code has been copied in the last few years and few days ago, and we really would like to have some explanations from Hexeption.

Affected files and proofs:
https://github.com/magmafoundation/Magma-1.16.x/blob/1.16.x/build.gradle#L815-L856
https://github.com/MohistMC/Mohist/blob/1.16.5/build.gradle#L780-L822

https://github.com/magmafoundation/Magma-1.16.x/blob/1.16.x/src/fmllauncher/java/org/magmafoundation/magma/installer/Installer.java
https://github.com/MohistMC/Mohist/blob/1.16.5/src/fmllauncher/java/com/mohistmc/util/InstallUtils.java

https://github.com/magmafoundation/Magma-1.16.x/blob/1.16.x/src/fmllauncher/java/org/magmafoundation/magma/utils/JarLoader.java
https://github.com/MohistMC/Mohist/blob/1.16.5/src/fmllauncher/java/com/mohistmc/util/JarLoader.java

https://github.com/magmafoundation/Magma-1.16.x/blob/1.16.x/src/fmllauncher/java/org/magmafoundation/magma/utils/JarUtils.java
https://github.com/MohistMC/Mohist/blob/1.16.5/src/fmllauncher/java/com/mohistmc/util/JarTool.java

And to finish, all of the Mohist remapper code appears in Magma as you can see in these two commit diffs. All files are exactly the same (only 2 or 3 have tiny diffs but it's still the same thing).

https://github.com/MohistMC/Mohist/commit/42f170746dc7c674dd03fd06dd385d265406692e#diff-b91e84c9b30a849cfac57977df844739de4e7807888bfb5ff1c9b0b62ab16e65
https://github.com/magmafoundation/Magma-1.16.x/commit/41091f5262e5d8ee045db6a6aeff5e4150ac7e90#diff-beb881d41ebe4d8bf528117bb6abffcf885c5ed0dcbc8cba6a181a9440feba55

Thank you for reading this, and we hope to get some explanations from the developers.

**Comment by Romaindu35** [comment]
???

**Comment by UeberallGebannt** [comment]
This issue has been resolved in private, I just want to add some clarity to this post:

We were working on an own installer for the server, which is inspired by the one Shawizz made, it was not our intention to just copy paste the code without credit. The complete version with credit given will be released soon.

**Comment by Romaindu35** [comment]
Ok 👍
