### ISSUE TITLE
[Bug]: Player loses perms on death

### ISSUE THREAD

**Issue by Jorue23** [magmafoundation/Magma-1.16.x#198]
### What happened?

So whenever a player dies all of the custom created perms seem to not be loaded again after respawning. We have tried it in different versions of magma and with different perm plugins. It seems like magma fails to load the perms after respawning.

### Mods

Neapolitan (by TeamAbnormals)
Botania (by Vazkii)
Curious Armor Stands (by ochotonida)
Waystones (by BlayTheNinth)
Cloth Config API (Forge) (by shedaniel)
ServerConfig Updater (by Darkere)
Transport (by Sky_Som)
Flux Networks (by sonar_sonic)
Performant (by someaddon)
mGui (by mickelus)
Extra Boats (by TeamAbnormals)
JEI Integration (by SnowShock35)
iChunUtil (by ohaiiChun)
Back Tools (by ohaiiChun)
Valhelsia Tweaks (by ValhelsiaTeam)
Client Tweaks (by BlayTheNinth)
Fruitful (Forge) (by team_aurora_modding)
Polymorph (Forge) (by TheIllusiveC4)
Apotheosis (by Shadows_of_Fire)
Miner's Helmet (by ModdingLegacy)
Inventory HUD+ (by dmitrylovin)
Valhelsia Structures (by ValhelsiaTeam)
Overloaded Armor Bar (by tfarecnim)
Structure Gel API (by ModdingLegacy)
Allurement (by TeamAbnormals)
AutoRegLib (by Vazkii)
Fast Furnace minus Replacement (by tfarecnim)
Blue Skies (by ModdingLegacy)
KubeJS (Forge) (by LatvianModder)
Immersive Petroleum (by Flaxbeard)
MythicBotany (by noeppinoeppi)
Step (by ModdingLegacy)
Macaw's Roofs (by sketch_macaw)
Citadel (by alex_khaan)
Controlling (by Jaredlll08)
Abnormals Core (by TeamAbnormals)
Open Loader (by DarkhaxDev)
Server Tab Info (by black_dog20)
The Conjurer (by ModdingLegacy)
Buzzier Bees (by TeamAbnormals)
Cooking for Blockheads (by BlayTheNinth)
Biomes O' Plenty (by Forstride)
Mekanism Additions (by bradyaidanc)
Titanium (by Buuz135)
Blood Magic (by WayofTime)
Environmental (by TeamAbnormals)
Mowzie's Mobs (by bobmowzie)
Valhelsia Core (by ValhelsiaTeam)
Notes (by Chaosyr)
Just Enough Items (JEI) (by mezz)
Druidcraft (by VulpTheHorseDog)
FerriteCore (Forge) (by malte0811)
Toast Control (by Shadows_of_Fire)
Entity Culling Fabric/Forge (by tr9zw)
Scuba Gear (by ModdingLegacy)
Fishing Real (by PricelessKoala)
Pane In The Glass (by MongoTheElder)
Mystical World (by Noobanidus)
LibX (by noeppinoeppi)
Bedspreads (Forge) (by TheIllusiveC4)
Akashic Tome (by Vazkii)
Snow! Real Magic! ⛄ (by Snownee_)
Mannequins (by oldjaackson)
Berry Good (by TeamAbnormals)
Abnormals Delight (by TeamAbnormals)
Psi (by Vazkii)
ExpandAbility (by florensie)
Nature's Compass (by Chaosyr)
Tetra (by mickelus)
Etched (by oldjaackson)
Atum 2: Return to the Sands (by Shadowclaimer)
Macaw's Fences and Walls (by sketch_macaw)
Archer's Paradox (by TeamCoFH)
CodeChicken Lib 1.8.+ (by covers1624)
Waddles (by Girafi)
KubeJS Create (by LatvianModder)
Torch Slabs Mod (by EndlesNights)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Nether's Delight (by lumpazl)
In Control! (by McJty)
Astral Sorcery (by HellFirePvP)
Forbidden and Arcanus (by cesar_zorak)
Personality (by TeamAbnormals)
Neat (by Vazkii)
Storage Drawers (by Texelsaur)
Better Burning (by DarkhaxDev)
KubeJS Blood Magic (by LatvianModder)
SuperMartijn642's Config Lib (by SuperMartijn642)
Just Enough Resources (JER) (by way2muchnoise)
Darker Depths (by naterbobber)
Mekanism (by bradyaidanc)
Atmospheric (by TeamAbnormals)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Curious Elytra (Forge) (by TheIllusiveC4)
Tomes (by VulpTheHorseDog)
CaveBiomeAPI [Forge] (by blackgear27)
Sound Device Options (by ichttt)
Flywheel (by jozufozu)
Cosmetic Armor Reworked (by LainMI)
Structurize (by H3lay)
DrawerFPS (by someaddon)
CC: Tweaked (by SquidDev)
Curios API (Forge) (by TheIllusiveC4)
Macaw's Windows (by sketch_macaw)
Ender Storage 1.8.+ (by covers1624)
Xaero's World Map (by xaero96)
Leap (by ModdingLegacy)
Advanced Peripherals (by srrendi)
The Mighty Architect (by simibubi)
Lollipop (by owmii)
Better Biome Blend (by FionaTheMortal)
Quark Oddities (by Vazkii)
Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)
Enhanced Mushrooms (Forge) (by team_aurora_modding)
Carry On (by Tschipp)
Differentiate (by eltrutlikes)
Seamless Loading Screen (Forge) (by TimScript)
Refined Storage: Requestify (by Buuz135)
Catalogue (by MrCrayfish)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
Decorative Blocks (by stohun)
Bed Benefits (by DarkhaxDev)
Farsighted Mobs (Forge) (by Sindarin27)
KleeSlabs (by BlayTheNinth)
OpenBlocks Elevator (by vsngarcia)
Netherite Horse Armor Mod (by louie_cai)
ConnectedTexturesMod (by tterrag1098)
Curios Quark Oddities Backpack (by 6LeoMC)
BetterF3 (by cominixo)
Decorative Blocks modded compat (by Evo_934)
Better Badlands (by Gkoliver)
BlockCarpentry (by PianoManu)
Bookshelf (by DarkhaxDev)
KubeJS Immersive Engineering (by LatvianModder)
Industrial Foregoing (by Buuz135)
Goblin Traders (by MrCrayfish)
Tool Stats (by DarkhaxDev)
Selene Lib (by MehVahdJukaar)
AI Improvements (by QueenOfMissiles)
Refined Storage (by raoulvdberge)
Enchanted Book Redesign (by tfarecnim)
Caelus API (Forge) (by TheIllusiveC4)
Eidolon (by elucent_)
Drawers Tooltip (by Snownee_)
Torchmaster (by xalcon)
Artifacts (by ochotonida)
Patchouli (by Vazkii)
Configured (by MrCrayfish)
Paintings ++ (by AbsolemJackdaw)
ObserverLib (by HellFirePvP)
AmbientSounds 4 (by CreativeMD)
Health Overlay (Forge) (by Terrails)
Upgrade Aquatic (by TeamAbnormals)
Immersive Engineering (by BluSunrize)
Quark (by Vazkii)
Crafting Tweaks (by BlayTheNinth)
YUNG's API (Forge) (by YUNGNICKYOUNG)
SwingThroughGrass (by exidex)
PackMenu (by Shadows_of_Fire)
Cookielicious (by Evo_934)
Connectible Chains [FORGE] (by lilypuree)
Simple Discord RPC [Forge/Fabric] (by hypherionsa)
Curio of Undying (Forge) (by TheIllusiveC4)
Music Maker Mod (by xerca0)
Immersive Posts (by TwistedGate)
Rhino (by LatvianModder)
Curious Shulker Boxes (Forge) (by TheIllusiveC4)
RandomPatches (Forge) (by TheRandomLabs)
Chocolate Fix (by AlcatrazEscapee)
Jade 🔍 (by Snownee_)
spark (by Iucko)
Peculiars (by catscythee)
Powah! (by owmii)
Create (by simibubi)
Chunk Loaders (by SuperMartijn642)
AppleSkin (by squeek502)
Tetranomicon (by syrikalis)
Better Title Screen (by Girafi)
Architectury API (Forge) (by shedaniel)
Aquaculture 2 (by Shadowclaimer)
Bamboo Blocks (by TeamAbnormals)
Savage & Ravage (by TeamAbnormals)
Cat Jammies (by Buuz135)
Farsight (by someaddon)
Farmer's Delight (by vectorwing)
Refined Storage Addons (by raoulvdberge)
Fast Leaf Decay (by olafskiii)
MineColonies (by H3lay)
Dusk (by someaddon)
The Twilight Forest (by Benimatic)
Iron Chests (by ProgWML6)
Mouse Tweaks (by YaLTeR)
KubeJS Mekanism (by LatvianModder)
ReAuth (by TechnicianLP)
Absent by Design (by Lothrazar)
Autumnity (by TeamAbnormals)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
CreativeCore (by CreativeMD)
Create Crafts & Additions (by MRHminer)
Default Options (by BlayTheNinth)
Dark Utilities (by DarkhaxDev)
Clumps (by Jaredlll08)
Xaero's Minimap (by xaero96)
Ensorcellation (by TeamCoFH)
Seasonals (by catscythee)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Kiwi 🥝 (by Snownee_)
Dynamic Surroundings (by OreCruncher)
Snow Under Trees (by bl4ckscor3)
Alex's Mobs (by alex_khaan)
Macaw's Furniture (by sketch_macaw)
Macaw's Bridges (by sketch_macaw)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Chisels & Bits (by AlgorithmX2)
FastWorkbench Minus Replacement (by tfarecnim)
Fairy Lights (by pau101)
TrashSlot (by BlayTheNinth)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
CoFH Core (by TeamCoFH)
Supplementaries (by MehVahdJukaar)
FTB Backups (Forge) (by FTB)
Neon Craft Mod (by Polyvalord)
Placebo (by Shadows_of_Fire)
AIOT Botania (by MelanX)
Macaw's Trapdoors (by sketch_macaw)
Comforts (Forge) (by TheIllusiveC4)
Connectivity (by someaddon)
Windowlogging (by mc_Grimmauld)
Dash (by ModdingLegacy)
Armor Toughness Bar (by tfarecnim)
Building Gadgets (by Direwolf20)
Cherished Worlds (Forge) (by TheIllusiveC4)
BetterEnd (Forge) (by Beethoven92)
Customizable Elytra (by Hidoni)
Extended Lights (by Polyvalord)
Dungeons Mobs (by the_infamous_1)
Bayou Blues (Forge) (by team_aurora_modding)
Abundance (by team_aurora_modding)
Runelic (by DarkhaxDev)
Better Advancements (by way2muchnoise)
The Endergetic Expansion (by TeamAbnormals)
JAOPCA (by TheLMiffy1111)
Macaw's Doors (by sketch_macaw)
Engineer's Decor (by wilechaote)
Tetra Pak (by Noobulus_Dos)

### Mod Version

abnormals_delight-1.16.5-1.2.0
advancedperipherals-1.16.5-0.7.3r
AI-Improvements-1.16.2-0.3.0
allurement-1.16.5-1.2.0
AmbientSounds_v3.1.10_mc1.16.5
Apotheosis-1.16.5-4.8.2
appleskin-forge-mc1.16.x-2.1.0
architectury-1.24.35-forge
Atum-1.16.5-2.2.8
bamboo_blocks-1.16.5-3.0.0
berry_good-1.16.5-4.1.1
BiomesOPlenty-1.16.5-13.1.0.482-universal
BloodMagic-1.16.4-3.1.5-25
Botania-1.16.5-419
caelus-forge-1.16.5-2.1.3.1
catalogue-1.3.0-1.16.5
cavebiomeapi-1.16.5-1.4.0
cc-tweaked-1.16.5-1.98.2
chiselsandbits-1.0.42-ALPHA
cloth-config-4.11.26-forge
CodeChickenLib-1.16.5-4.0.3.434-universal
configured-1.2.0-1.16.3
connectivity-2.3-1.16.5
Controlling-7.0.0.27
CosmeticArmorReworked-1.16.5-v4
create-mc1.16.5_v0.3.2f
createaddition-1.16.5-20211023a
curiouselytra-forge-1.16.5-4.0.2.3
customizableelytra-1.16.4-1.5.7
engineersdecor-1.16.4-1.1.14
extraboats-1.16.5-2.1.0
FarmersDelight-1.16.5-0.5.1
flywheel-1.16-0.2.4
forbidden_arcanus-16.2.0-beta-4
iChunUtil-1.16.5-10.4.1
ImmersivePetroleum-1.16.5-3.3.0-7
incontrol-1.16-5.2.1
ironchest-1.16.5-11.2.13
JAOPCA-1.16.5-3.4.1.15
jeed-1.16.5-1.3
jei-1.16.5-7.7.1.129
JustEnoughResources-1.16.5-0.12.1.128
Kiwi-1.16.5-3.6.0
kubejs-forge-1605.3.18-build.152
mcw-bridges-1.0.6-mc1.16.5
Mekanism-1.16.5-10.0.22.449
MekanismAdditions-1.16.5-10.0.22.449
MekanismGenerators-1.16.5-10.0.22.449
MekanismTools-1.16.5-10.0.22.449
minecolonies-1.0.87-ALPHA-universal
mysticalworld-1.16.5-0.3.5.23
MythicBotany-1.16.5-1.4.14
performant-1.16.2-5-3.72m
personality-1.16.5-1.0.2
Placebo-1.16.5-4.6.0
polymorph-forge-1.16.5-0.25
Quark-r2.4-319
refinedstorage-1.9.15
refinedstorageaddons-0.7.3
rhino-forge-1605.1.4-build.67
selene-1.16.5-1.8.1
ServerTabInfo-1.16.4-1.3.3
simple-rpc-1.16.5-2.5
SnowRealMagic-1.16.4-2.7.2.
structurize-0.13.252-ALPHA-universal
supplementaries-1.16.5-0.17.7
tetra-1.16.5-3.18.0
titanium-1.16.5-3.2.8.5-20
tomes-1.2
upgrade_aquatic-1.16.5-3.1.0
valhelsia_tweaks-16.0.9
Waystones_1.16.5-7.6.3
windowlogging-mc1.16.3_v0.0.4
Xaeros_Minimap_21.20.0_Forge_1.16.5
XaerosWorldMap_1.18.0_Forge_1.16.5
absentbydesign-1.16.5-1.5.1
Abundance-1.16.5-1.0.5
aiotbotania-1.16.5-1.8.4
AkashicTome-1.4-16
alexsmobs-1.12.1
Aquaculture-1.16.5-2.1.21
archers_paradox-1.16.5-1.3.1
toughnessbar-6.1
Artifacts-1.16.5-2.10.3
astralsorcery-1.16-1.16.5-1.13.12
atmospheric-1.16.5-3.1.0
AutoRegLib-1.6-49
autumnity-1.16.5-2.1.1
BackTools-1.16.5-10.1.0
bwncr-1.16.5-3.10.16
Bayou-Blues-1.16.5-1.0.5
BedBenefits-1.16.5-5.0.4
bedspreads-forge-1.16.5-5.1.0.3
BetterAdvancements-1.16.5-0.1.1.115
Better-Badlands-1.16.5-2.0.3
betterbiomeblend-1.16.4-1.2.9-forge
BetterBurning-1.16.5-6.0.7
BetterTitleScreen-1.16.4-1.10.2
betterendforge-1.16.5-1.6.3
BetterF3-1.1.3-forge-1.16.5
blockcarpentry-1.16-0.4.0
blue_skies-1.16.5-1.1.3
abnormals_core-1.16.5-3.3.0
Bookshelf-Forge-1.16.5-10.3.29
buildinggadgets-1.16.5-3.8.2
buzzier_bees-1.16.5-3.0.1
carryon-1.16.5-1.15.5.15
catjammies-1.1.0
cherishedworlds-forge-1.16.5-5.1.1.0
chocolate-1.3.0-1.16.4
chunkloaders-1.1.7-mc1.16.5
citadel-1.8.1-1.16.5
ClientTweaks_1.16.3-5.3.0
Clumps-6.0.0.27
cofh_core-1.16.5-1.3.1
comforts-forge-1.16.5-4.0.1.3
CTM-MC1.16.1-1.1.2.6
connectiblechains-1.2.0
cookielicious-1.16.5-1.4.3
CookingForBlockheads_1.16.5-9.3.4
CraftingTweaks_1.16.5-12.2.1
CreativeCore_v2.2.1_mc1.16.5
curioofundying-forge-1.16.5-5.2.0.0
curios-forge-1.16.5-4.0.5.3
CuriosQuarkOBP-1.16.5-1.0.2
Curious Armor Stands-1.16.5-2.1.2
curiousshulkerboxes-forge-1.16.5-4.0.1.0
DarkUtilities-1.16.5-8.0.11
darkerdepths-1.16.5-1.1.4
dash-1.16.4-1.0.1
decorative_blocks-1.16.4-1.7.2
decorative_blocks_abnormals-1.2
DefaultOptions_1.16.5-12.2.1
differentiate-1.16.5-0.5.3
drawerfps-2.1
DrawersTooltip-1.16.2-2.1.1
Druidcraft-1.16.5-0.4.54
dungeons_mobs-1.16.5-1.0.10
dusk-1.4
DynamicSurroundings-1.16.5-4.0.5.0
enchantedbookredesign-3.3-1.16.4
eidolon-0.2.7
EnderStorage-1.16.5-2.8.0.168-universal
Enhanced-Mushrooms-1.16.5-3.0.9
ensorcellation-1.16.5-1.3.1
entityculling-1.3.0
environmental-1.16.5-1.1.0
etched-1.1.0-1.16.5-forge
expandability-2.0.1-forge
extlights-3.3
fairylights-4.0.5-1.16.5
farsight-1.7
farsightedmobs-forge-1.16-1.1
fastfurnaceminusreplacement-1.1-1.16.3
FastLeafDecay-v25
fastbenchminusreplacement-1.4
ferritecore-2.1.0-forge
fishingreal-1.16.3-1.0.0
FluxNetworks-1.16.5-6.1.7.12
Fruitful-1.16.5-2.1.0
ftb-backups-2.1.2.2
goblintraders-1.6.0-1.16.3
HealthOverlay-1.16.5-3.0.1
ImmersiveEngineering-1.16.5-5.0.5-140
immersiveposts-1.16.5-4.2.2
industrial-foregoing-1.16.5-3.2.14.6-14
InventoryHud_[1.16.2-1.16.5].forge-3.4.1
Jade-1.16.4-2.8.0
jeiintegration_1.16.5-7.0.1.15
KleeSlabs_1.16.5-9.2.1
kubejs-blood-magic-1605.1.1-build.3
kubejs-create-1605.1.2-build.7
kubejs-immersive-engineering-1605.1.1-build.2
kubejs-mekanism-1605.1.2-build.2
lazydfu-0.1.3
leap-1.16.4-1.1.1
LibX-1.16.3-1.0.76
light-overlay-5.8.1
Lollipop-1.16.5-3.2.9
mcw-doors-1.0.3-mc1.16.5
mcw-fences-1.0.1-mc1.16.5
mcw-furniture-2.0.1-mc1.16.5
mcw-roofs-2.0.1-mc1.16.5-4
mcw-trapdoors-1.0.3-mc1.16.5
mcw-windows-2.0.0-mc1.16.5
mannequins-1.0.1-1.16.5-forge
mgui-1.16.5-3.3.0
mining_helmet-1.16.5-2.0.1
MouseTweaks-2.14-mc1.16.2
mowziesmobs-1.5.19
xercamusic-1.16.5-1.4
NaturesCompass-1.16.5-1.9.1-forge
neapolitan-1.16.5-2.1.0
Neat 1.7-27
neoncraft-2.0
nethers_delight-2.1
netheritehorsearmor-1.7
Notes-1.16.5-1.2.3
observerlib-1.16.5-1.5.3
OpenLoader-1.16.5-9.0.3
elevatorid-1.16.5-1.7.13
overloadedarmorbar-5.1.0
PackMenu-1.16.5-2.5.0
paintings-1.16.4-7.0.0.1
pitg-1.16.5-2.0.1
Patchouli-1.16.4-53.2
peculiars-1.16.5-2.0.0
Powah-1.16.5-2.3.16
Psi 1.16-97
QuarkOddities-1.16.3
randompatches-2.4.4-forge
ReAuth-1.16-Forge-3.9.3
rsrequestify-1.16.5-2.1.4
Runelic-1.16.5-7.0.2
savageandravage-1.16.5-3.1.0
scuba-gear-1.16.5-1.0.3
seamless_loading_screen-1.16.5-1.1.6
seasonals-1.16.5-2.0.0
serverconfigupdater-1.3
snowundertrees-1.16.5-v1.3
sounddeviceoptions-1.4.3
spark-forge
step-1.16.4-1.1.0
StorageDrawers-1.16.3-8.3.0
structure_gel-1.16.5-1.7.8
supermartijn642configlib-1.0.9-mc1.16
swingthroughgrass-1.16.4-1.5.3
tetrapak-1.16.5-0.3.3
tetranomicon-1.3
the-conjurer-1.16.4-1.0.13
endergetic-1.16.4-3.0.0
mightyarchitect-mc1.16.3_v0.5.
twilightforest-1.16.5-4.0.546-universal
Toast-Control-1.16.4-4.3.1
ToolStats-1.16.5-6.0.4
torchslabmod-1.16.4_v1.6.19
torchmaster-2.3.8
Transport-1.16.5-3.7.0
TrashSlot_1.16.3-12.2.1
valhelsia_core-16.0.13a
valhelsia_structures-1.16.5-0.1.6
Waddles-1.16.5-0.8.13
YungsApi-1.16.4-Forge-13
BetterCaves-Forge-1.16.4-1.1.2
BetterMineshafts-Forge-1.16.4-2.0.4
BetterStrongholds-1.16.4-1.2.1

### Plugins

Will follow asap

### Magma Version

Version: vc7f6ff3

### OS

Linux

### Relevant log output

[05Dec2021 05:02:53.979] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: DigitalCraver issued server command: /back [05Dec2021 05:03:04.656] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: Gathering id map for writing to world save world [05Dec2021 05:03:04.687] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: ID Map collection complete world [05Dec2021 05:03:07.413] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: DigitalCraver issued server command: /back [05Dec2021 05:03:15.711] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: DigitalCraver was blown up by Creepie [05Dec2021 05:03:17.262] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@446558d5 [05Dec2021 05:03:17.458] [Server thread/DEBUG] [twilightforest/]: Player DigitalCraver (98699088-5a63-4aa1-b230-57a62fc46f17) respawned and received items held in storage [05Dec2021 05:03:20.853] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: DigitalCraver issued server command: /back [05Dec2021 05:03:20.855] [Server thread/INFO] [Essentials/]: DigitalCraver was denied access to command. [05Dec2021 05:03:22.752] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: DigitalCraver issued server command: /back [05Dec2021 05:03:22.752] [Server thread/INFO] [Essentials/]: DigitalCraver was denied access to command. [05Dec2021 05:03:23.646] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: DigitalCraver issued server command: /back [05Dec2021 05:03:23.647] [Server thread/INFO] [Essentials/]: DigitalCraver was denied access to command.

**Comment by MagnusHJensen** [comment]
Could you try and replicate with only essentials and luckperms or something?

**Comment by UeberallGebannt** [comment]
This issue is known currently

**Comment by scarlettcloud** [comment]
I reported an issue here: https://github.com/magmafoundation/Magma-1.16.x/issues/219#issue-1165444548 related to another issue with EssentialsX /warp and /tp commands; is it possible that this issue is causing mine? What was the resolution?
