### ISSUE TITLE
Yung's Better Caves crash at start

### ISSUE THREAD

**Issue by zoyer2** [magmafoundation/Magma-1.16.x#20]
Version: forge-1.16.3-34.1.19-3549466
BetterCaves-1.16.2-1.0.3
Issue: Crash at starting
[latest.log](https://github.com/magmafoundation/Magma-1.16-Issues/files/5384800/latest.log)
[debug.log](https://github.com/magmafoundation/Magma-1.16-Issues/files/5384801/debug.log)

**Comment by UeberallGebannt** [comment]
Could you retry on the latest version?

**Comment by neptune-gaming** [comment]
the latest version doesn't seem to have any issues with yung's better caves, or any other mods from the same modmaker

**Comment by UeberallGebannt** [comment]
Ok, so everythings working now? If yes, I will close this issue

**Comment by neptune-gaming** [comment]
yes. it works now.

**Comment by UeberallGebannt** [comment]
Ok, thank you, I will close this then
