### ISSUE TITLE
[Bug]: Broken animal spawning

### ISSUE THREAD

**Issue by ByMessias** [magmafoundation/Magma-1.16.x#201]
### What happened?

Basically what happens is that after we create a world, as the chunks are loaded the spawning of animals increases and this becomes more and more frequent.
Here are some images:
![2021-12-08_11 30 09](https://user-images.githubusercontent.com/94620261/145335600-7014b9b4-e2a2-439c-93a1-07ca8ecf42a4.png)
![2021-12-08_12 17 47](https://user-images.githubusercontent.com/94620261/145335648-2c5a58b5-829b-47b5-986a-0a1f84578e77.png)
![2021-12-08_12 18 12](https://user-images.githubusercontent.com/94620261/145335717-139ba4e2-df7c-4392-b22e-368077916dc2.png)

### Mods

none

### Mod Version

none

### Magma Version

1.16.5-9c6363d-DEV
1.16.5-b0de73e-DEV
1.16.5-c7f6ff3-STABLE

### OS

Linux

**Comment by lowerforce77** [comment]
have the same problem in v5a1cac0 and v75c9e73
