### ISSUE TITLE
[Vanilla] /difficulty command

### ISSUE THREAD

**Issue by Cixon** [magmafoundation/Magma-1.16.x#24]
**desc:** _in a server with one or more users, changing difficulty in real time is pretty bad. so bad that some people will still receive attacks from mobs and even hear them for a small period but they aren't there. the command does not permanently work either._
**tester_note: it could be connectivity issues. not 100%, I suggest you test it yourself.**

**Comment by kwright02** [comment]
I have tried to replicate this but it doesn't seem to happen.
