### ISSUE TITLE
[Forgemods] CRASH: Sitting Mechanics in mods. (ironagefurniture/mrcrayfish/sit mod/etc)

### ISSUE THREAD

**Issue by Cixon** [magmafoundation/Magma-1.16.x#27]
**desc:** _I've tested the popular [Mrcrayfish's](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod) furniture mod and even underrated furniture mods like [IronAgeFurniture](https://www.curseforge.com/minecraft/mc-mods/ironagefurniture). No matter which furniture you choose, as soon as you interact with a stool, chair, couch anything that makes the player sit the server simply DIES._

**Comment by UeberallGebannt** [comment]
Could you retry on the latest version?

**Comment by UeberallGebannt** [comment]
Tested with MrCrayFish, works fine in latest release
