### ISSUE TITLE
[Vanilla & Forgemods] Shield blocking functionality

### ISSUE THREAD

**Issue by Cixon** [magmafoundation/Magma-1.16.x#35]
**desc:** _When blocking with a modded and vanilla shield_ (_[bettershields](https://www.curseforge.com/minecraft/mc-mods/better-shields)_)_, the shield does not deplete it's durability._

_To add onto this, blocking is overall very buggy._

**Comment by jahangir6969** [comment]
https://youtu.be/uf-MFBGMZx8 

I have tested shield in 1.16.4 just vanilla not the mod and it was fine for me. Please see video above.

**Comment by Cixon** [comment]
With further investigation, issue has seem to be the mods fault. Issue closed.

**Comment by Cixon** [comment]
With further investigation, issue has seem to be the mods fault. Issue closed.
