### ISSUE TITLE
Some bugs / errors bug plugins

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#38]
Describe the bug:
server contains several errors with the magma.

Log-latest: https://mclo.gs/woK2dbB
Log-debug: https://mclo.gs/2RJnOou

List plugins error magma:
PlaceholderAPI
eGlow
CombatLogX
ProtocolLib
BlockLocker
LuckPerms
Vault
WorldEdit
SkinsRestorer
OpeNLogin
ClearLag
IllegalStack
SinglePlayerSleep
CustomDeathMessages
AdvancedDonations
SpawnerManager
CrazyCrates
PetMaster
VeinMiner
Multiverse-Core]
AdvancedAchievements 
WorldGuard 
MythicMobs 
Quests 
Skript
Jobs v4.16.2
SkQuery v4.1.4
EliteMobs
RedProtect 
ChestShop
RandomTeleport

Magma Version: Magma: forge-1.16.3-34.1.19-9fafe52-installer.jar (latest early access build as of 11/01/20)
OS: Windows 10

**Comment by Hexeption** [comment]
All theses mods have been tested except the premium plugins and look to be working
