### ISSUE TITLE
server crasher

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#40]
Describe the bug:
When I enter the server, the same crasher

Log-crash-reports: https://mclo.gs/duYSxiG
Log-debug: https://mclo.gs/tKURW4B
Log-latest : https://mclo.gs/o4rJvg3

Magma Version: Magma: forge-1.16.3-34.1.19-9fafe52-installer.jar (latest early access build as of 11/01/20)
OS: Windows 10

**Comment by Hexeption** [comment]
Fixed
