### ISSUE TITLE
[Magma] Latest Biomes You'll Go mod not supported anymore

### ISSUE THREAD

**Issue by Cixon** [magmafoundation/Magma-1.16.x#42]
### Describe the bug

While attempting to load the latest BYG version (1.1.1) the server throws error fail to start.

### To Reproduce

1.) Install latest magma-1.16.3-34.1.35-2a697a4
2.) Add [v1.1.1 BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3098350) mod.
3.) See log.

### Expected behavior
Server loading successfully, functional server.

**Additional context:** I tried older build of BYG (v1.0.8) but it's now buggy and causes client lag.
Not to mention, this latest build fixes a lot of its own problems which is why Magma should support it.

### Logs
[debug.log](https://github.com/magmafoundation/Magma-1.16-Issues/files/5471609/debug.log)
[latest.log](https://github.com/magmafoundation/Magma-1.16-Issues/files/5471610/latest.log)

**Comment by Cixon** [comment]
Still occurs for latest Magma 1.16.4 build. Tested on [byg-1.1.2](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3100031)

**Comment by Hexeption** [comment]
Fixed
