### ISSUE TITLE
[Vanilla] Book and Quill does not get signed / Lectern working weird. 

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#47]
Describe the bug
A clear and concise description of what the bug is:

Book and quill does not get signed. Do not know what else to say.

To Reproduce

Signed Book and Quill

Expected behavior
A clear and concise description of what you expected to happen:

For an book to be sign off and does not repeat itself. It has an issue with them in lectern as well: (copy from 1.15.2) When placing books on the lectern and try to pick it up the gui stay on and it has weird effect where sometime the book come back and other times it does not.

Screenshots
If applicable, add screenshots to help explain your problem:

Book signing: https://youtu.be/rp_eWSaclSo >> 1.15.2 video but can do the same to happened in 1.16.3

Lecturn issue: https://gyazo.com/6806b2d7b2d25ad19e84afc452e5930c 

Console Logs:

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.3 forge 34.1.42
Magma Version: forge-1.16.3-34.1.35-2a697a4
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

Also an issue in 1.15.2: https://github.com/magmafoundation/Magma-1.15.x/issues/63

**Comment by jahangir6969** [comment]
Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM

**Comment by jahangir6969** [comment]
https://gyazo.com/8626b79424ef824ee2a29910979df9b3

**Comment by kwright02** [comment]
Still working on the book and quill fix, but I have managed to fix the lectern issue! I'll keep you posted
