### ISSUE TITLE
[Vanilla] The end Dragon has 1hp aka will die if it get hit with an explosion. (This issue extend to any Vanilla Boss) 

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#49]
Describe the bug
A clear and concise description of what the bug is:

The end dragon kills right away from explosion

To Reproduce
Steps to reproduce the behaviour:

Blow it up with some kind of explosion 

Expected behaviour
A clear and concise description of what you expected to happen:

For it not to died with one explosion

Screenshots
If applicable, add screenshots to help explain your problem:

no screenshot. it an record: https://youtu.be/zaybqBmcTh0

Console Logs:

Nope

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.3 forge 34.1.42
Magma Version: forge-1.16.3-34.1.35-2a697a4
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

**Comment by joaoespanhol** [comment]
https://www.youtube.com/watch?v=ghby6ynJZQ4&feature=youtu.be

**Comment by jahangir6969** [comment]
This issue after speaking with @joaoespanhol extend to any Vanilla Bosses

**Comment by jahangir6969** [comment]
Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM. 

This is with both the wither and dragon.
