### ISSUE TITLE
[Vanilla] Enderman likes to swim in the water

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#57]
Describer problem: Enderman likes to swim in the water
he doesn't leave water, he must teleport

https://www.youtube.com/watch?v=mjY7tdRieS4&feature=youtu.be

Mod Name: no mods
Mod Version: no mods
OS: Windows 10
Magma version 1.16.4-35.0.0-fb9f494

**Comment by jahangir6969** [comment]
https://gyazo.com/df1d5bf1b77efa35c206a7bf42ebbd62

Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM

**Comment by fel1x0u** [comment]
Lmfao, the enderman is staying in the water
