### ISSUE TITLE
Crash with RandomPatches

### ISSUE THREAD

**Issue by jinkhya** [magmafoundation/Magma-1.16.x#58]
**Describe the bug**
A clear and concise description of what the bug is:
RandomPatches seems to crash the server on load.

**To Reproduce**
1. Setup a server with random patches and Magma
2. Start the server.
Crash

**Expected behavior**
A clear and concise description of what you expected to happen:
to not crash :)

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: RandomPatches
 - Mod Version: randompatches-1.16.2-1.22.1.2.jar
 - Magma Version: magma-1.16.3-34.1.35-2a697a4
 - OS: Ubuntu 20.04.1

**Additional context**
Crash log : https://mclo.gs/sWJZ2n3

**Comment by neptune-gaming** [comment]
Could you retry in a newer version?

**Comment by Hexeption** [comment]
Fixed
