### ISSUE TITLE
[BUG] Plugin Bssentials

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#59]
plugin with error magma

Log-Latest: https://mclo.gs/dBkp5wV
Log-Debug: https://mclo.gs/8dIZ4Bb

Link plugin: https://www.spigotmc.org/resources/bssentials-essentials-1-8-1-16.25576/updates
OS: Windows 10
Magma version 1.16.4-35.0.0-fb9f494

**Comment by Hexeption** [comment]
Fixed
