### ISSUE TITLE
[vanilla] trident breaks blocks when in the creative

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#60]
Describer problem: tested vanilla first, does not break blocks, tested by magma server, it breaks blocks, more video information

Video: https://youtu.be/yThDsREdDm4

This server is running Magma version 1.16.4-35.0.0-fb9f494
OS: windows 10

**Comment by jahangir6969** [comment]
Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM
