### ISSUE TITLE
[Vanilla] bug minecart tnt

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#61]
Describer bug:
put minecart with tnt on top of the rail and push it once, it activates and explodes, but inside server magma it doesn't happen

Link video: https://www.youtube.com/watch?v=F7DPnDzjq7k&feature=youtu.be
tested it off the server is after the server

OS windows 10
Magma version 1.16.4-35.0.0-fb9f494

**Comment by kwright02** [comment]
The only thing I see here is that in single-player the blocks with rails on them don't get blown up, but the reason you're seeing an "instant" prime of the TNT is because you have 1 detector rail in your single player setup, and you didn't in multiplayer. cheers.

**Comment by joaoespanhol** [comment]
> The only thing I see here is that in single-player the blocks with rails on them don't get blown up, but the reason you're seeing an "instant" prime of the TNT is because you have 1 detector rail in your single player setup, and you didn't in multiplayer. cheers.

you are absolutely right.
I came back to test and there is no bug.
i close ticket
