### ISSUE TITLE
[MOD] Vampirism-1.16.3-1.6.1 error console

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#64]
Server have error console mod.

![image](https://user-images.githubusercontent.com/22871432/98437776-f2015680-20dc-11eb-95f9-04984a4f9c24.png)

Log-debug: https://mclo.gs/wt8uEJH
Log-laster: https://mclo.gs/9RiYbOE

Versão mod:Vampirism-1.16.3-1.6.1 
OS: windows 10
Version magma: 1.16.4 last version.

**Comment by Hexeption** [comment]
Fixed
