### ISSUE TITLE
[MOD] BloodMagic-1.16.3-3.0.0-1 Error console

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma-1.16.x#65]
Describer problem

[MOD] Error console mod: BloodMagic-1.16.3-3.0.0-1
Log-laster: https://mclo.gs/FrQU4Of
Log-debug: https://mclo.gs/5pfZ89O

Name mod: BloodMagic-1.16.3-3.0.0-1

Magma version: 1.16.4 last version
Os: windows 10

**Comment by Hexeption** [comment]
Fixed
