### ISSUE TITLE
[Vanilla]Wearing turtle Cap give the water breathing timer an spaz attack

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#72]
Describe the bug
A clear and concise description of what the bug is:

The timer when going into the inventory menu when wearing a turtle hat a spaz attach

To Reproduce
Steps to reproduce the behaviour:

Wear and turtle hat when in the inventory menu

Expected behaviour
A clear and concise description of what you expected to happen:

For it not to have a spaz attack

Screenshots
If applicable, add screenshots to help explain your problem:

https://youtu.be/kUfswjLhwZs

Console Logs:

None

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.4 forge 35.0.18
Magma Version: magma-1.16.4-35.0.18-7DF0AB4
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

**Comment by jahangir6969** [comment]
Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM

**Comment by jahangir6969** [comment]
https://gyazo.com/f51d3faef3cfa6e30784d9f1482953b4

**Comment by kwright02** [comment]
Fixed
