### ISSUE TITLE
[Vanilla] unable to stay in creative after relogging

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#73]
Describe the bug
A clear and concise description of what the bug is:

For some reason I was thinking I create this ticket already, but for some reason, I did not, but the issue is when you relog it does not remember to keep you in the game mode you were In and places you back into survival. 

To Reproduce
Steps to reproduce the behaviour:

go another game mode that is not survival and relog and you see it

Expected behaviour
A clear and concise description of what you expected to happen:

Remeber to keep you in the same gamemode

Screenshots
If applicable, add screenshots to help explain your problem:

Nope

Console Logs:

Nope

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.4 forge 35.0.18
Magma Version: magma-1.16.4-35.0.18-7DF0AB4
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

Same issue within 1.15: https://github.com/magmafoundation/Magma-1.15.x/issues/61

**Comment by That-Guy-Jack** [comment]
What does your server.properties look like ?

**Comment by wolflord212312** [comment]
do you have any plugins like essentials?

If you have essentials i think there is a config for it

**Comment by jahangir6969** [comment]
You do not need to ask me question lol. As it an bug within 1.16 it is set to survival in server.prop but it just an broken vanilla bug.

**Comment by jahangir6969** [comment]
Also as you can see in the title of the issue. It says vanilla mean just magma no plugins or mods. If it an plugin I have logged it under [plugin] keep the ticket logs nice and clean to know what the issue is :)

**Comment by Lordfirespeed** [comment]
If you have `force-gamemode` Set to `true` In server.properties this is supposed to happen. Please send your server.properties file contents inside code delimiters

**Comment by kwright02** [comment]
I couldn't reproduce this issue

**Comment by jahangir6969** [comment]
Can confirm no longer an issue. Ticket can be closed.
