### ISSUE TITLE
Mobs die everytime the chunk loads

### ISSUE THREAD

**Issue by jusobreira** [magmafoundation/Magma-1.16.x#82]
This footage was with a magma server with NO MODS. Just the jar.. Everytime i pass the chunk this happens whit no errors at the console.

[2021-02-03 00-14-14.zip](https://github.com/magmafoundation/Magma-1.16.x/files/5915864/2021-02-03.00-14-14.zip)

**Comment by UeberallGebannt** [comment]
Should be fixed in latest release, could you retry?

**Comment by jusobreira** [comment]
Thanks for your reply but i'm not patreon anymore. Sorry, I can't help you with tests.

**Comment by UeberallGebannt** [comment]
Magma 1.16 isnt Patreon exclusive anymore, you can download it on the discord ^^

**Comment by jahangir6969** [comment]
Will test myself, And confirm this.
