### ISSUE TITLE
[vanilla] Bounce effect when dropping items or splashing EXP bottle

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#86]
**Describe the bug**
A clear and concise description of what the bug is:

When you drop items or splash yourself with an xp bottle. it start to do the shifting button/bouncing up and down thing

**To Reproduce**
Steps to reproduce the behaviour:

Drop items or splash yourself with xp

**Expected behaviour**
A clear and concise description of what you expected to happen:

Not to bounce/do the shift feature

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/a07f2695a31000a154b8f4439276c594

https://gyazo.com/69e52ba24d91cd5848d307ddb67b5ac8

Also here is the logs for it as well:

no errors

**Info (please complete the following information):**
Mod Name: no mods
Mod Version: no mods
Client forge version: forge-1.16.5-36.1.0
Magma Version: forge-1.16.5-36.1.0-c6d0ef4-CUSTOM
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
i'm going to mark this as minor and not really something that needs to be fixed
