### ISSUE TITLE
[Vanilla] Splash potion of harming does not damage yourself

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#87]
**Describe the bug**
A clear and concise description of what the bug is:

When you splash yourself with harming splash potions. the player does not take damage.

**To Reproduce**
Steps to reproduce the behaviour:

Get splash potion of harming and splash on yourself

**Expected behaviour**
A clear and concise description of what you expected to happen:

To taken damage with it

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/629742fd22539ca342c6b640308c106c

Also here is the logs for it as well:

no error. 

**Info (please complete the following information):**
- Mod Name: no mods 
 - Mod Version: no mods
 - Client forge version: forge-1.16.5-36.1.0
 - Magma Version: forge-1.16.5-36.1.0-c6d0ef4-CUSTOM
 - OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
Couldn't reproduce

**Comment by jahangir6969** [comment]
Again can confirm. Seems to be a weird bug but it seems to fix it self up. So closing ticket down.
