### ISSUE TITLE
[Vanilla] Player head spam console

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#90]
**Describe the bug**
A clear and concise description of what the bug is:

Placing player head using /give pokekhan minecraft:player_head error out console when placing or breaking

**To Reproduce**
Steps to reproduce the behaviour:

place heads down. 

**Expected behaviour**
A clear and concise description of what you expected to happen:

For it not to spam console and for them to work

**Screenshots**
If applicable, add screenshots to help explain your problem:

N/A

Also here is the logs for it as well:
https://pastebin.com/T7RbEx0H

**Info (please complete the following information):**
- Mod Name: no mods 
 - Mod Version: no mods
 - Client forge version: forge-1.16.5-36.1.0
 - Magma Version: forge-1.16.5-36.1.0-c6d0ef4-CUSTOM
 - OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
couldn't reproduce

**Comment by jahangir6969** [comment]
Can confirm no longer an issue. Closing ticket down but if I can reproduce it will reopen it.
