### ISSUE TITLE
[Vanilla] Entity collision is broken

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#93]
**Describe the bug**
A clear and concise description of what the bug is:

When I was testing the sheep dye issue. I came across another issue where when the try to push me and it could not and had a weird non-push effect instead of myself/the sheep move around. So I test with a few animals like sheep, cow and chickens and same with other mobs like a zombie as there just no way for me to push them around. 

**To Reproduce**
Steps to reproduce the behaviour:

Push entity like a cow or an zombie

**Expected behaviour**
A clear and concise description of what you expected to happen:

For you be able to push mobs around using the entity collision. 

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/7f2b453d54a65d637c144ae312901721

Also here is the logs for it as well:

no error

**Info (please complete the following information):**
- Mod Name: no mods 
 - Mod Version: no mods
 - Client forge version: forge-1.16.5-36.1.0
 - Magma Version: forge-1.16.5-36.1.0-c6d0ef4-CUSTOM
 - OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
marking as minor
