### ISSUE TITLE
[Vanilla] Growing jungle tree is broken (Crashes when big tree spawns)

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#97]
**Describe the bug**
A clear and concise description of what the bug is:

When growing small or big tree error errors console. When growing small tree it does not spawn it correctly. When it comes to the big jungle tree. the moment it gens in the big tree it crashes server

**To Reproduce**
Steps to reproduce the behaviour:

Grow jungle tree

**Expected behaviour**
A clear and concise description of what you expected to happen:

For it to grow trees and not to error in console

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://youtu.be/iDZKIAWB7jc

Also here is the logs for it as well:

https://pastebin.com/LJdQyv0m

**Info (please complete the following information):**
- Mod Name: no mods 
 - Mod Version: no mods
 - Client forge version: forge-1.16.5-36.1.0
 - Magma Version: forge-1.16.5-36.1.0-c6d0ef4-CUSTOM
 - OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by jahangir6969** [comment]
Error when big tree spawns: https://pastebin.com/tp4sTTjQ

**Comment by kwright02** [comment]
I couldn't even spawn trees, the saplings just turn into green buttons

**Comment by UeberallGebannt** [comment]
I could reproduce that a while ago, seems like the tree type for this exact jungle tree isn't correctly implemented, even found the code that sets it but wasn't able to find the error
